### ISSUE TITLE
Материалы про драйвера

### ISSUE THREAD

**Issue by Tima32** [XShar/Windows_Kernel_Programming#1]
Сдравствуйте, что можете посоветовать еще почитать про доайвера?

**Comment by XShar** [comment]
Доброго времени !

Можно почитать более качественный перевод тут:[https://www.piter.com/collection/kompyutery-i-internet/product/rabota-s-yadrom-windows](https://www.piter.com/collection/kompyutery-i-internet/product/rabota-s-yadrom-windows)

Также хорошо почитать книги Марка Руссиновича:[https://www.piter.com/product_by_id/110274978?recommended_by=dynamic&recommended_code=46ce9b64036c53acd60bfc7a38ecdaf2](https://www.piter.com/product_by_id/110274978?recommended_by=dynamic&recommended_code=46ce9b64036c53acd60bfc7a38ecdaf2)

Также не плохо смотреть сорцы:[https://github.com/microsoft/Windows-driver-samples](https://github.com/microsoft/Windows-driver-samples)

В целом этого должно хватить...)

**Comment by Tima32** [comment]
Спасибо.

Хотелось бы чего-нибудь про не документированные функции (например: SeLocateProcessImageName) да и в целом про всякие разные штучки :)

Я студент 3 курса, хочу сделать темой своей дипломной работы античит системы. Уже есть реализованный минимальный набор функций. Возможно у вас будет какая-нибудь информация про реализацию крупных античитов, она бы мне очень пригодилась для развития проекта. Свистелок-перделок много не бывает ;) Да и для всякой чернухи эта информация пригодилась бы.

Также хотелось бы выразить благодарность за ваш github, он кладезь информации, найти его было словно наткнуться на золотую жилу.
